### ISSUE TITLE
ItemsAdder + SF plugin and another (i cant place blocks)

### ISSUE THREAD

**Issue by matyasvane** [Slimefun/Slimefun4#3373] opened 2021-12-13 20:18 UTC
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

I have more plugins on the server, but gradually removing it failed to detect an error.

(if i have Slimefun plugin on the server, i cant place itemsadders block intro another. The problem is that when I start removing plugins and then I want to add any other (even LuckPerms) there is a problem that I can't lay blocks (if it is on the Slimefun server)

Alternatively, please help which plugins I should remove what may be causing the issues. Honestly? On the server I had:

And after adding the Vault plugin there was a problem (completely nonsensical)

I've been solving this problem for a month now and I haven't been able to fix the error. Please help.

![image](https://user-images.githubusercontent.com/75536352/145883788-98e589d6-4ee1-4829-b187-3a17aec7cdf3.png)

### 📑 Reproduction Steps

1. Install ItemsAdder and Slimefun (with another 21 plugins) and after place on the itemsadder block vanilla blocks.

### 💡 Expected Behavior

You cant place vanilla block on the itemsadder blocks

### 📷 Screenshots / Videos

https://www.youtube.com/watch?v=GoqjhGT1wsU

### 📜 Server Log

https://pastebin.com/QKpcjFgE

### 📂 `/error-reports/` folder

Nothing

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.17.x

### ⭐ Slimefun version

![image](https://user-images.githubusercontent.com/75536352/145882104-62a21ade-e92f-4c17-b4ab-478afcc469fb.png)

### 🧭 Other plugins

![image](https://user-images.githubusercontent.com/75536352/145882296-79fa10a6-d375-408d-9033-a913e38657a3.png)

**Comment by JustAHuman-xD** [comment] 2023-03-02 13:21
Is this still an issue? I also don't think this is caused by Slimefun if it is but instead by one of the other plugins

**Comment by variananora** [comment] 2023-03-02 13:45
> Is this still an issue? 

Cant test it since I dont have IA license.

**Comment by JustAHuman-xD** [comment] 2023-03-02 14:05
> > Is this still an issue? 
> 
> 
> 
> Cant test it since I dont have IA license.

I believe there is a free version

**Comment by matyasvane** [comment] 2023-03-05 23:19
> Is this still an issue? I also don't think this is caused by Slimefun if it is but instead by one of the other plugins

Nope, its fixed. Before, I was using a custom plugin for this that it created via shrink packets :D

**Comment by variananora** [comment] 2023-03-06 03:54
Thanks for the info, I'll close this issue as resolved.

**Closed by variananora** 2023-03-06 03:54 UTC
Labels: 🐞 Bug Report, 🎯 Needs testing
