### ISSUE TITLE
All Slimefun items that are represented as heads break when placed

### ISSUE THREAD

**Issue by Boomer-1** [Slimefun/Slimefun4#3840] opened 2023-06-09 05:01 UTC
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

When a server is in a version below 1.19.4, and a player logs in above 1.19.3, if they place any machine, regulator, capacitor, cargo node, any item that is represented with a head, while wearing a helmet, having only 1 of the item in their hand when placed will cause the item to turn into a cs-corelib head. Jeff believes the cause of this maybe, because it's a head and you have a helmet on the listener cancels and the blockplaceevent doesn't happen. 

He mentioned this may be tied to the issue.
https://github.com/ViaVersion/ViaVersion/commit/734bc9e88c06c6432fb734983add7ecd3ef11039

### 📑 Reproduction Steps

start server below 1.19.4
client logs in to server with 1.19.4 or higher
viaversion must be on the server
player must have a helmet on (enchants not needed)
player goes to place a slimefun item that is an actual head, holding only 1 of the item
when placed it turns into cs-corelib head.

### 💡 Expected Behavior

the item when placed to remain the item.

### 📜 Server Log

no errors

### 📂 `/error-reports/` folder

none

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.19.x

### ⭐ Slimefun version

dev 1056

**Comment by variananora** [comment] 2023-06-09 06:23
Just tested it like Jeff requested, seems like that https://github.com/ViaVersion/ViaVersion/commit/734bc9e88c06c6432fb734983add7ecd3ef11039 toggle caused this. 

By disabling `armor-toggle-fix` on ViaVersion's `config.yml` this bug doesn't occurred anymore.

**Comment by Sefiraat** [comment] 2023-06-09 07:17
I have been testing this so much, with so many different variables and IT WAS BECAUSE I WASN'T WEARING ARMOR!?

I could cry

**Comment by J3fftw1** [comment] 2023-06-09 07:34
> I have been testing this so much, with so many different variables and IT WAS BECAUSE I WASN'T WEARING ARMOR!?
> 
> I could cry

I would have never expected this but apparently 1.19.4 added a function where you could swap armour pieces somehow.

**Comment by WarnDa** [comment] 2023-06-19 18:47
Opened an issue on viaversion side, os hopefully they will fix this on their own.
I don't know which issue disabling armor-toggle-fix can cause, if you know ?

**Comment by J3fftw1** [comment] 2023-06-19 18:49
> Opened an issue on viaversion side, os hopefully they will fix this on their own. I don't know which issue disabling `armor-toggle-fix` can cause, if you know ?

honestly no clue, im not even sure what it even does when enabled.

**Comment by WarnDa** [comment] 2023-06-19 18:52
> > Opened an issue on viaversion side, os hopefully they will fix this on their own. I don't know which issue disabling `armor-toggle-fix` can cause, if you know ?
> 
> honestly no clue, im not even sure what it even does when enabled.

Asked a friend who disabled the option, you can't just switch armor using right click, that's the only "drawbacks"

**Comment by Sefiraat** [comment] 2023-06-19 18:54
If you’re happy with that downside then we have had reports it fixes the issue for you, the only reason we’ve not openly recommended it yet is we’ve not found the time to know the effects of the toggle, but if you’re right it seems like an ok temporary sacrifice.

**Comment by WarnDa** [comment] 2023-06-19 18:55
Yes if it doesn't create duplication, or other downside effect, it's very minor.
Very happy that you mentionned this issue, so I know the fix, and I know it's a real issue :D

**Comment by Sefiraat** [comment] 2023-06-19 18:57
Don’t ha, we took so long working out the cause. Due to it being only when wearing a helmet with a single item in the stack it meant the reports coming in were so varied and it looked like a transient issue. We really got lucky someone made the helmet connection which made it all fall into place.

**Comment by Sefiraat** [comment] 2023-06-22 09:23
ViaVersion have pushed an update which looks to have fixed this specific issue (https://github.com/ViaVersion/ViaVersion/commit/4971eeab6a4967ae25a80246436a12547224cccb). I will check later when I'm free but if anyone wants to confirm the fix before this, you'll need the most recent version of ViaVersion (Build 711, ViaVersion-4.7.1-SNAPSHOT.jar)

**Comment by Sefiraat** [comment] 2023-06-22 09:49
Confirmed as fixed in the latest ViaVersion dev build - simply download that and you'll be back to normal with the toggle enabled!
Thanks for the report <3

**Closed by Sefiraat** 2023-06-22 09:49 UTC
Labels: 🐞 Bug Report, 🧨 Confirmed Bug
