### ISSUE TITLE
aternos 1.16.5 slimefun 4 bugged af

### ISSUE THREAD

**Issue by SLIMEFUNHELPMEE** [Slimefun/Slimefun4#3630] opened 2022-07-26 21:12 UTC
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

when i turn on the server or restart is the slimefun mod crashes and it dosnt work :/ i cant seem to fix it apart from just downloading another version and once i use that version and turn onn the server again it buggs and it dosnt work. im in a spigot 1.16.5 aternos server the crash code is: <html>
<body>

[15:57:56] [Server thread/ERROR]: Could not load 'plugins/Slimefun4-1026.jar' in folder 'plugins'
--
15 | org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: io/github/thebusybiscuit/slimefun4/implementation/Slimefun has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 52.0

</body>
</html>

### 📑 Reproduction Steps

idk man pls help meeeee

### 💡 Expected Behavior

i expect for you to help me? i dont expect you to be fast just help me

### 📷 Screenshots / Videos

![helpppp](https://user-images.githubusercontent.com/110064734/181112324-a20a33f5-cb6d-4113-bbff-6ae6166f7dc5.png)

### 📜 Server Log

[15:57:56] [Server thread/ERROR]: Could not load 'plugins/Slimefun4-1026.jar' in folder 'plugins' org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: io/github/thebusybiscuit/slimefun4/implementation/Slimefun has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 52.0

### 📂 `/error-reports/` folder

This folder is empty. idk why :/

### 💻 Server Software

Spigot

### 🎮 Minecraft Version

1.16.x

### ⭐ Slimefun version

slimefun 4

### 🧭 Other plugins

i dont have any other plugin apart from 
Better-Enchantments

**Comment by ybw0014** [comment] 2022-07-26 21:13
Update your Java

**Comment by Boomer-1** [comment] 2022-07-26 21:17
additionally we are not responsible for anything on aternos. This is not a bug report and i am closing this.

**Closed by Boomer-1** 2022-07-26 21:17 UTC
Labels: invalid
