### ISSUE TITLE
Hologram Duplication

### ISSUE THREAD

**Issue by lostsys** [Slimefun/Slimefun4#3556] opened 2022-05-08 08:02 UTC
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

I was just making a joke server crate at my base. They use an ender chest so I put that on top and put the holograms underneath to make the crate text. When adjusting the height I had gotten the hologram stuck trying to fix it I messed with both because they seemed to affect each other, then it duplicated. 

### 📑 Reproduction Steps

1. Get two Hologram Projects and an ender chest.
2. Stack three blocks e-chest on top with two projectors below.
3. You then push the holograms up, one may get stuck.
4. Messing with the holograms height seems to cause the duplication.

### 💡 Expected Behavior

I was just expecting it to go through the enderchest like any other block I've done it with. 

### 📷 Screenshots / Videos

https://youtu.be/idXAxIa5Z3Q - unlisted video showing the bug, not exactly sure what causes it though.

### 📜 Server Log

Not my server, maybe the developer of the server will add further input if he sees this
EDIT: nothing

### 📂 `/error-reports/` folder

as above
EDIT: none

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.18.x

### ⭐ Slimefun version

1.18.2 RC 31

### 🧭 Other plugins

Honestly not sure, when I have time later I'll add slimefun alone on a private server and recreate it to see. 

EDIT: https://youtu.be/fXTsOWp4r3Q - most recent SF version with only SF and ViaVersion installed

**Comment by Boomer-1** [comment] 2022-05-08 12:18
Duplicate of #3176. please add pertinent information to that report.

**Closed by Boomer-1** 2022-05-08 12:18 UTC
Labels: 🚩 Duplicate
