### ISSUE TITLE
Slimefun Crash when Autosaving

### ISSUE THREAD

**Issue by KennethRhodes8213** [Slimefun/Slimefun4#3480] opened 2022-03-07 21:13 UTC
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [ ] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

I was looking at my server logs and found this interesting crash when Slimefun was auto-updating.
[https://pastebin.com/cZtaUpmg](https://pastebin.com/cZtaUpmg)

### 📑 Reproduction Steps

Autosave

### 💡 Expected Behavior

It to not crash.

### 📜 Server Log

https://pastebin.com/mKA74u4i

### 📂 `/error-reports/` folder

N/A

### 💻 Server Software

Spigot

### 🎮 Minecraft Version

1.18.x

### ⭐ Slimefun version

Spigot 3446-Spigot-fb0dd5f-6e75502 (MC: 1.18.2)
Slimefun RC - 30 (git fd4b462f)
Metrics-Module #28
Java 17

**Comment by Sefiraat** [comment] 2022-03-07 21:22
Minecraft version 1.18.2 is not yet supported due to the changes to NMS between versions. A fix is in the works and I’m sure an announcement will come out when it is supported.

**Comment by TheBusyBiscuit** [comment] 2022-03-08 11:07
Nor do we support RC versions of Slimefun.
Update to the latest version of Slimefun first, if the issue persists, feel free to open a new bug report.

But as @Sefiraat stated the issue is due to the fact that MC 1.18.2 is not yet supported, a compatibility fix will be released in the coming hours or days.

**Closed by TheBusyBiscuit** 2022-03-08 11:07 UTC
Labels: invalid
