### ISSUE TITLE
Explosive Pickaxe drop note block when breaking custom ore from ItemsAdder

### ISSUE THREAD

**Issue by DarrienZ** [Slimefun/Slimefun4#4153] opened 2024-02-28 15:06 UTC
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

When I break custom ore using SlimeFun Explosive pickaxe it drops note block.

### 📑 Reproduction Steps

![image](https://github.com/Slimefun/Slimefun4/assets/108975040/657bc88a-c7c8-4008-8165-18830ae21426)

### 💡 Expected Behavior

This happened on other SF Addons before.

### 📷 Screenshots / Videos

https://github.com/Slimefun/Slimefun4/assets/108975040/0113188a-c973-430c-a19e-0d9f511beb9c

### 💻 Server Software

Purpur

### 🎮 Minecraft Version

1.20.x

### ⭐ Slimefun version

SLIMEFUN DEV - 1141

### 🧭 Other plugins

ItemsAdder

**Comment by Boomer-1** [comment] 2024-03-13 15:55
> #4008

these may or may not be related as they have different outcomes.

**Comment by Boomer-1** [comment] 2024-03-13 16:02
the other report didn't mention noteblocks. it said ores being duplicated. however watching the video, ores didn't drop, but noteblocks did. I'll update

**Comment by Boomer-1** [comment] 2024-03-13 16:06
closing as it's a duplicate of #4008

**Closed by Boomer-1** 2024-03-13 16:06 UTC
Labels: 🐞 Bug Report, 🚩 Duplicate
