### ISSUE TITLE
Ancient Altar will rename potion items

### ISSUE THREAD

**Issue by xMikux** [Slimefun/Slimefun4#3507] opened 2022-03-27 06:38 UTC
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

Ancient Altar will rename the potion, splash potion, lingering potion and potion arrow name.

### 📑 Reproduction Steps

1. Place potion type item to Ancient Altar
2. Take it down
3. See it will show include `[]` item name

### 💡 Expected Behavior

Don't rename the any potion type items, and take back will show normal vanilla item name.

### 📷 Screenshots / Videos

Before put on the Ancient Altar
![image](https://user-images.githubusercontent.com/26039249/160269522-5599f06a-7d1c-4439-993d-2fcc57705aef.png)
![image](https://user-images.githubusercontent.com/26039249/160269566-da83a661-bc27-40e8-bda0-573eb1c53166.png)
![image](https://user-images.githubusercontent.com/26039249/160269740-65f02a6a-4a3f-4cae-983a-b8e4c5a51c58.png)
![image](https://user-images.githubusercontent.com/26039249/160269756-bd7ae9f4-0cd9-4175-801e-8eb75ae04958.png)

After take down from the Ancient Altar
![image](https://user-images.githubusercontent.com/26039249/160269573-f09094ab-098b-4e73-8a45-2acbd4e74342.png)
![image](https://user-images.githubusercontent.com/26039249/160269579-654686a0-07e5-48b2-93f8-5c5b79e24bc1.png)
![image](https://user-images.githubusercontent.com/26039249/160269746-c7fc6e7a-32b8-4d4e-a715-447133a56cc0.png)
![image](https://user-images.githubusercontent.com/26039249/160269763-171d2870-a7e6-441e-96eb-823ebe0d6ee5.png)

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.18.x

### ⭐ Slimefun version

![image](https://user-images.githubusercontent.com/26039249/160269604-5ad2fc9f-96d2-4163-ab4d-122eeaaf29c0.png)

**Comment by Creependerman** [comment] 2023-06-17 07:47
I think it's maybe because of NBT. The screenshot show the NBT was changed by Ancient Altar.

**Comment by Creependerman** [comment] 2023-06-17 08:19
Yes, my guess is real. I saw though the AncientPedestal.java, when you place item, the Ancient Altar turn the item into entity. Then you take it down,  Ancient Altar turn the entity into item. So the item will be change.

**Comment by Creependerman** [comment] 2023-06-17 08:24
I think the better way is make the Ancient Altar memory the item.

**Comment by JustAHuman-xD** [comment] 2023-06-17 08:27
I can probably throw a fix for this into my existing PR. I'll do that tomorrow (today? It's three thirty am) 👍

**Comment by JustAHuman-xD** [comment] 2023-06-17 14:54
Does this only happen for potions?

**Comment by JustAHuman-xD** [comment] 2023-06-17 14:58
Found the cause, should be simple enough to fix

**Closed** 2023-07-12 12:21 UTC
Labels: 🐞 Bug Report, 🧨 Confirmed Bug
