### ISSUE TITLE
Crop Growth Accelerator does not work with Organic Fertilizer, if a texture pack is used

### ISSUE THREAD

**Issue by o7-hmoe** [Slimefun/Slimefun4#4113] opened 2024-01-28 01:39 UTC
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

The crop growth accelerator does not work if you input a fertilizer that has a custom model data, as defined in item-models.yml of the slimefun folder. The crop growth accelerator DOES however work if the value is set to 0 in item-models.yml.

### 📑 Reproduction Steps

1. Place down a crop growth accelerator and provide power and crops nearby. My set up is shown below
![image](https://github.com/Slimefun/Slimefun4/assets/21300105/d0d36a57-6a8a-4eee-8813-4f4caaa0874b)
2. Change the value for FERTILIZER_SEAGRASS in item-models.yml in the Slimefun folder. I changed mine to 5. NOTE that you do not need to have a valid texture. Applying any custom model data will prevent the fertilizer from working.
3. Restart the server to apply the new item model to FERTILIZER_SEAGRASS
4. Give yourself the fertilizer with /sf give <name> FERTILIZER_SEAGRASS
5. Put the fertilizer in the crop growth accelerator
6. Nothing will happen- the fertilizer cannot be used when it has a custom model data.

### 💡 Expected Behavior

The expected behaviour is that the crop growth accelerator should be able to work with organic fertilizer, even if the fertilizer has custom model data as defined in item-models.yml of the slimefun folder.

### 📷 Screenshots / Videos

![image](https://github.com/Slimefun/Slimefun4/assets/21300105/53a74424-d90f-4c89-bf21-f9cad07e8f40)
![image](https://github.com/Slimefun/Slimefun4/assets/21300105/50f38050-f572-48ea-a462-14937c446fa4)

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.20.x

### ⭐ Slimefun version

![image](https://github.com/Slimefun/Slimefun4/assets/21300105/c5cc4606-f73f-48c9-ab26-349a79df0fd3)

**Comment by Boomer-1** [comment] 2024-01-28 02:52
closing as this is a duplicate of #3446

**Closed** 2024-01-28 02:53 UTC
Labels: 🐞 Bug Report, 🚩 Duplicate, 🎯 Needs testing
