### ISSUE TITLE
butcher android wont get emeralds from vindicators

### ISSUE THREAD

**Issue by mahdi28881** [Slimefun/Slimefun4#3849] opened 2023-06-12 01:42 UTC
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

hello and thank you for this amazing mod
me and my cousin have been playing on a slimefun server and we set up a vindicator farm with a couple of vindicator spawners but the butcher android only collects the banners we have tested it with other mods and it collects their drops but it doesn't seem to collect vindicator emeralds drops to be precise. im posting it in suggestion and bug discussion as suggested

### 📑 Reproduction Steps

set up a vindicator farm with a couple of vindicator spawners
setup the empowered butcher android and turn it on

### 💡 Expected Behavior

it should collect all the loot like emeralds and axes but it only collects banners

### 🎮 Minecraft Version

1.20.x

### ⭐ Slimefun version

1.19.4-r01
DEV - 1051 (git 45346442)

**Comment by Boomer-1** [comment] 2023-06-12 01:43
i can confirm the android does not collect anything but banners.

**Comment by desumn** [comment] 2023-06-27 20:44
Minecraft Wiki says: "0–1 emeralds when killed by the player."

It won't drop emerald as is, it could be fixed by having the android attack as the player that own it?

**Comment by Sefiraat** [comment] 2023-06-27 20:50
Currently the only player-only kill drops are exceptions for blaze and wither skeletons, all others are explicitly not implemented. So while this is working as intended (currently) I am tempted for, perhaps, an other tier of android or something that does.

**Closed** 2023-12-06 13:49 UTC
Labels: 🐞 Bug Report, 🧨 Confirmed Bug
