### ISSUE TITLE
ItemsAdder items transferred via cargo

### ISSUE THREAD

**Issue by 100petr** [Slimefun/Slimefun4#3133] opened 2021-06-21 18:03 UTC
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

Slimefun cargo adds texture to the renamed item

### 📑 Reproduction Steps

I have in the ItemsAdder item named Coin with a texture on the stick. ![image](https://user-images.githubusercontent.com/29830635/122803443-e9a20880-d2c6-11eb-800f-b20696108463.png)
I'll put the coin in the first chest
I'll put a stick renamed to Coin in the second chest
I'll have the stick renamed Coin transferred via cargo
The stick acquires the texture of the coin
(Coin (ENG) = Mince (CZ))

We tried it with other items and it works like this with everything.

### 💡 Expected Behavior

The item transferred through the cargo does not acquire texture

### 📷 Screenshots / Videos

The videos were more than 10MB and could not be uploaded, I give a link to youtube
https://youtu.be/I1baDR_b1YQ
https://youtu.be/1-mUxS-7ADA

### 📜 Server Log

N/A

### 📂 `/error-reports/` folder

N/A

### 💻 Server Software

Purpur

### 🎮 Minecraft Version

1.16.x

### ⭐ Slimefun version

![image](https://user-images.githubusercontent.com/29830635/122803067-74363800-d2c6-11eb-9f3a-78dd9198cbc7.png)

### 🧭 Other plugins

![image](https://user-images.githubusercontent.com/29830635/122803100-7c8e7300-d2c6-11eb-8798-f2c8ba04e5ab.png)

**Comment by LoneDev6** [comment] 2021-06-21 19:30
Hello, I'm the developer of ItemsAdder, if any of Slimefun devs need a license for ItemsAdder I can provide it for free, just send me your Spigot username here

**Comment by LoneDev6** [comment] 2021-09-22 15:03
This is surely something that is not related to ItemsAdder directly.
I'm not handling the stacking of items in any way.
Probably Slimefun has an item matcher function which doesn't check also for CustomModelData but only for lore and display name, this is the cause of the wrongly merged items

**Comment by J3fftw1** [comment] 2021-09-22 15:07
> 
> 
> This is surely something that is not related to ItemsAdder directly.
> I'm not handling the stacking of items in any way.
> Probably Slimefun has an item matcher function which doesn't check also for CustomModelData but only for lore and display name, this is the cause of the wrongly merged items

we do actually check for this. I can be wrong tho
https://github.com/Slimefun/Slimefun4/blob/master/src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/blocks/BlockPlacer.java#L110

**Comment by J3fftw1** [comment] 2021-09-22 15:09
mmh wait i might have found the issue. Not sure tho since i cant test.
as said in my previous comment we do check for custom item but not for custom block on that if statement.

**Comment by Sfiguz7** [comment] 2021-09-22 15:15
That would still be for the BlockPlacer though. In this case, the player is trying to place by hand (and the underlying item is an iron ingot so there should be no BlockPlaceEvent being called, just PlayerInteractEvents)

**Comment by J3fftw1** [comment] 2021-09-22 15:16
Yea i got it wrong

**Comment by Sefiraat** [comment] 2021-09-22 15:21
I’m happy to test this later today and try to work out what is actually firing when this is attempted?

**Comment by Sfiguz7** [comment] 2021-09-22 15:44
I may have found the issue, will give a follow up comment about it

**Comment by Sefiraat** [comment] 2021-09-22 15:47
Ah good, i've just seen its like £15 so i likely wouldn't have likely gotten anywhere xD

**Closed** 2022-01-18 16:52 UTC
Labels: 🐞 Bug Report, 🎯 Needs testing

**Comment by LoneDev6** [comment] 2022-01-18 16:53
Thanks for the update, but I think custommodeldata check is not enough.
Some items might have the same custommodeldata but may be different custom items.

**Comment by WalshyDev** [comment] 2022-01-18 16:54
This is alongside name checks and other things. Are those enough to make sure it's unique? If not, do you have a suggestion?

**Comment by TheBusyBiscuit** [comment] 2022-01-18 16:55
I feel like if the "material, name, lore and customModelData" are all identical, it should be identical in 99.9999999999% of cases.
If not, we can always add another comparison layer or just a direct integration when a new issue about it pops up.

**Comment by LoneDev6** [comment] 2022-01-19 14:58
For now you can rely on the CustomModelData + DisplayName and Lore, I think it's enough for now.
