### ISSUE TITLE
Multi Tool - IV Lead Bug

### ISSUE THREAD

**Issue by SrMonsterYT** [Slimefun/Slimefun4#3662] opened 2022-08-23 23:43 UTC
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

when using the grappling hook mode, a multi too - IV, you right click several times fast and get multiplying lead.

just click really fast

image: https://prnt.sc/33MNhGoHbmtW
image 2: https://prnt.sc/pZ0iBj8yoYV1

slimefun version and server: https://prnt.sc/urJjsNyRZMP5

### 📑 Reproduction Steps

click really fast with the multi tool - IV in close blocks.

### 💡 Expected Behavior

do not drop leads on the ground, nor arrows

### 📷 Screenshots / Videos

image: https://prnt.sc/33MNhGoHbmtW
image 2: https://prnt.sc/pZ0iBj8yoYV1

### 📜 Server Log

no erro

### 📂 `/error-reports/` folder

no erro

### 💻 Server Software

Other (please specify in your description)

### 🎮 Minecraft Version

1.19.x

### ⭐ Slimefun version

Slimefun DEV - 1027 (git 96c873bd)

### 🧭 Other plugins

slimefun version and server: https://prnt.sc/urJjsNyRZMP5

**Comment by Boomer-1** [comment] 2022-08-24 00:53
can you get a video instead of an image? images don't really show anything happening

**Comment by variananora** [comment] 2022-08-24 03:30
Duplicate of https://github.com/Slimefun/Slimefun4/issues/2352

**Closed by variananora** 2022-08-24 03:30 UTC
Labels: 🐞 Bug Report, 🎯 Needs testing

**Comment by SrMonsterYT** [comment] 2022-08-24 13:55
is there a fix for this?

**Comment by Boomer-1** [comment] 2022-08-24 15:29
no. it is open in issue #2352
