### ISSUE TITLE
Slimefun4 Search function not working when bungeechat2 is installed

### ISSUE THREAD

**Issue by Noobymen** [Slimefun/Slimefun4#3710] opened 2022-10-29 20:58 UTC
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

when typing /slimefun open_guide and clicking in the top right corner on search and then just typing the search term in chat it just comes up as if you are normally chatting in game

### 📑 Reproduction Steps

just instal slimefun4 and bungeechat2 togheter and do what i just say

### 💡 Expected Behavior

hopeplly this can be fixst 

### 📜 Server Log

no errors

### 📂 `/error-reports/` folder

no errors

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.19.x

### ⭐ Slimefun version

DEV 1035

### 🧭 Other plugins

Bungee Chat 2.2.3

**Comment by ybw0014** [comment] 2022-10-29 23:27
cannot reproduce this

**Comment by Noobymen** [comment] 2022-10-30 00:02
Use watterfall and paper latest versions

**Comment by Boomer-1** [comment] 2022-10-30 00:11
you can't use two different servers at the same time. you can use paper or waterfall

**Comment by Noobymen** [comment] 2022-10-30 00:17
Sorry what i mean is test it on paper version server and waterfall and see if can reproduce on one off them

**Comment by Boomer-1** [comment] 2022-10-30 00:18
not going to try it on something you didn't experience a problem on

**Comment by Noobymen** [comment] 2022-10-30 00:19
I did experience it

**Comment by Boomer-1** [comment] 2022-10-30 00:19
you said paper, so not going to test waterfall

**Comment by Boomer-1** [comment] 2022-10-30 00:20
i'm quite sure ybw tested it based on the information you provided.

**Comment by ybw0014** [comment] 2022-10-30 00:20
well it seems bungeechat is blocking chat messages to be sent to server

**Comment by Noobymen** [comment] 2022-10-30 00:21
Sorry maybe my info is wrong am talking about waterfall

**Comment by Boomer-1** [comment] 2022-10-30 00:22
bungeechat is throwing errors in my log. i'd look for a more updated version of it

**Comment by Boomer-1** [comment] 2022-10-30 00:24
in my testing it is not happening either. I'm on the latest slimefun and paper in 1.19.2. closing as we cannot reproduce this. bungee chat is over 2 years old based on 2.2.3. i'd see if there is a more recent version, and talk to the dev

**Comment by Noobymen** [comment] 2022-10-30 00:24
Dont know where to find that the only one i can find is the one on spigot

**Closed by Boomer-1** 2022-10-30 00:24 UTC
Labels: invalid

**Comment by Boomer-1** [comment] 2022-10-30 00:26
it has problems based on the errors it threw in my server console. I'd talk to the dev to see if they've done some updates, as it isn't working right.

**Comment by ybw0014** [comment] 2022-10-30 00:26
Bungee chat is blocking messages on waterfall side, not a slimefun problem.

**Comment by Noobymen** [comment] 2022-10-30 00:27
Alright thank you very much keep me updated on that thanks again

**Comment by Boomer-1** [comment] 2022-11-02 16:53
this error has nothing to do with slimefun or bungeechat. it is in your launcher settings for chat.

**Comment by Noobymen** [comment] 2022-11-02 17:04
My launcher settings for chat?
You mean just the settings in game that you can choose to hide the chat?

**Comment by Boomer-1** [comment] 2022-11-02 18:42
when i removed bungeechat from my server, which never even loaded because it's got some issues, i got the error. when chat is set to commands only, it happened. when I set chat to shown, it went away

**Comment by Noobymen** [comment] 2022-11-02 19:03
My chat settings is always on shown and am still having the problem so

**Comment by variananora** [comment] 2022-11-03 00:38
> this error has nothing to do with slimefun or bungeechat. it is in your launcher settings for chat.

No, bungeechat blocks the chat in Waterfall/Bungeecord so the Spigot/Paper server will not get the messages. This is like what ybw said.

**Comment by Boomer-1** [comment] 2022-11-03 01:43
thats odd, as I was able to create the exact same scenario without the chat addon. It may also be a vanilla issue or mojang issue
