### ISSUE TITLE
SlimefunGuideMode.CHEAT_MODE doesn't fire

### ISSUE THREAD

**Issue by JustinDevB** [Slimefun/Slimefun4#3464] opened 2022-02-12 20:09 UTC
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

@EventHandler
    public void slimefunGuideOpen(SlimefunGuideOpenEvent event) {
        mcpe.log("Mode: " + event.getGuideLayout().toString(), true);
        if (event.getGuideLayout() != SlimefunGuideMode.CHEAT_MODE)
            return;
            
 When doing /sf cheat this never returns CHEAT_MODE, nothing is printed. 
 Haven't looked through the source, but I'm guessing that the /sf cheat command does not fire the SlimefunGuideOpenEvevnt event and then set the Enum to CHEAT_MODE

### 📑 Reproduction Steps

@EventHandler
    public void slimefunGuideOpen(SlimefunGuideOpenEvent event) {
        mcpe.log("Mode: " + event.getGuideLayout().toString(), true);
        if (event.getGuideLayout() != SlimefunGuideMode.CHEAT_MODE)
            return;

Run /sf cheat
nothing will print. Open a regular guide and it prints SURVIVAL_MODE  This should fire and print CHEAT_MODE when opening the cheat menu

### 💡 Expected Behavior

SlimefunGuideOpeneEvent fires on /sf cheat and Enum is properly set to CHEAT_MODE

### 💻 Server Software

Purpur

### 🎮 Minecraft Version

1.18.x

### ⭐ Slimefun version

![Capture](https://user-images.githubusercontent.com/6395878/153726734-4dfbee65-5fc2-4a30-b8ef-6e078f0874e7.PNG)

**Comment by JustAHuman-xD** [comment] 2023-07-29 17:11
is this actually a bug or would we say this is intended? The event requires an itemstack which is @Nonnull and the problem is the command has no itemstack, we would also need a new message to be sent to the player if the event was cancelled otherwise they are going to think the command is just broken.

**Comment by JustinDevB** [comment] 2023-07-29 18:26
No idea if this is intended or not. I opened this over a year ago with no response. Completely forgot everything about it.

**Comment by iTwins** [comment] 2023-08-08 23:19
so the 'issue' here is the `/sf open_guide` and `/sf cheat` commands not calling the ``SlimefunGuideOpenEvent`` event?

**Comment by JustAHuman-xD** [comment] 2023-08-08 23:22
> so the 'issue' here is the `/sf open_guide` and `/sf cheat` commands not calling the `SlimefunGuideOpenEvent` event?

Yes but in reality imo it shouldnt, the event has a nonnull itemstack for the guide passed also if the event is cancelled we would need a message or something sent to the player that way they dont just think the command is broken

**Comment by iTwins** [comment] 2023-08-08 23:37
The nonnull itemstack means we can't really change this. There is no itemstack when using the command, but making it nullable would very likely break a lot of implementations. Only option would be providing a dummy itemstack, but that would be kind of ugly.

**Comment by JustAHuman-xD** [comment] 2023-08-08 23:52
> The nonnull itemstack means we can't really change this. There is no itemstack when using the command, but making it nullable would very likely break a lot of implementations. Only option would be providing a dummy itemstack, but that would be kind of ugly.

Bingo

**Comment by JustAHuman-xD** [comment] 2023-11-11 20:50
Going to go ahead and close this due to the aforementioned issues

**Closed by JustAHuman-xD** 2023-11-11 20:50 UTC
Labels: 🐞 Bug Report
