### ISSUE TITLE
Some Simefun Plates like GPS ACTIVATION PLATE SHARED/PERSONAL and Also Elevator Plate being Duplicated if i break with explosive pickaxe

### ISSUE THREAD

**Issue by mathew75757** [Slimefun/Slimefun4#4206] opened 2024-06-10 03:02 UTC
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

i found a bug if i break the GPS 

https://github.com/Slimefun/Slimefun4/assets/88549407/d03b732d-eb96-486c-b148-f4e7d6eecad2

ACTIVATION DEVICE (SHARED) with explosive pickaxe it will dupe for some reason

### 📑 Reproduction Steps

Prepare a base, 1.20.4, paper server.
No configuration needs to be made to the server, minus eula=true
Launch the server. and try to break the Elevator plate or GPS ACTIVATION DEVICES plate as showned in VIDEO.

Uploading 2024-06-09 17-13-56 (1).mp4…

### 💡 Expected Behavior

I expected to fix the issue of being dupe of some item plates 

### 📷 Screenshots / Videos

https://github.com/Slimefun/Slimefun4/assets/88549407/7bf90db5-7e12-4773-a455-28f36334c862

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.20.x

### ⭐ Slimefun version

Slimefun DEV - 1148

**Comment by Boomer-1** [comment] 2024-06-10 03:05
duplicate of #4037

**Closed by Boomer-1** 2024-06-10 03:05 UTC
Labels: 🚩 Duplicate
