### ISSUE TITLE
Players Lost Backpack Data Updating Slimefun

### ISSUE THREAD

**Issue by GitNuck** [Slimefun/Slimefun4#4141] opened 2024-02-23 20:10 UTC
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

I updated the Server to Dev Build 1139 and some players lost their backpacks.  The data has been completely scrubbed from the Player's .yml file.  What is odd is only certain players have lost their backpacks, others are fine.  What I do know is that these Players most likely use a modded Client, so this may be part of the issue somehow.

### 📑 Reproduction Steps

Certain players try and access their backpack and have, "CS-CoreLib's Head" displayed instead.

### 💡 Expected Behavior

Players able to access their backpacks.

### 📷 Screenshots / Videos

![cscorehead](https://github.com/Slimefun/Slimefun4/assets/88690764/e6581846-71e0-42aa-b2c6-4aeb9d728c72)

### 📜 Server Log

No error messages

### 💻 Server Software

Purpur

### 🎮 Minecraft Version

1.20.x

### ⭐ Slimefun version

![2024-02-23_13 08 06](https://github.com/Slimefun/Slimefun4/assets/88690764/98d2b206-0db6-4341-b6fd-7baf2b1a8115)

### 🧭 Other plugins

![2024-02-23_13 09 36](https://github.com/Slimefun/Slimefun4/assets/88690764/12eb4ddc-562f-4a59-a3fe-b5d40df40247)

**Comment by Boomer-1** [comment] 2024-02-23 20:18
can you confirm that the alleged missing backpacks were created by those players? the person who crafted them has their id assigned to it, not the person who uses it. it may help to track that info down

**Comment by Boomer-1** [comment] 2024-02-23 20:35
one other thought - did any other players join after you updated to 1139, whose backpacks were fine?

**Comment by GitNuck** [comment] 2024-02-23 20:38
They did indeed craft those backpacks, I am sure that one of the mods, a Fabric inventory mod called "itemscroller" was the issue.  It plays with inventory entries so that had to be the issue.  I use InventoryRollbackPlus on the Server and it saved the day, I was able to recover the Player's backpacks complete with the inventory inside.  I'll mark this closed as I'm 99.99% sure that the mod was responsible.
![inventorey scroller](https://github.com/Slimefun/Slimefun4/assets/88690764/9ff6bcec-21a7-449b-a241-d6f27f4d3173)

**Comment by GitNuck** [comment] 2024-02-23 20:39
Thanks for the help!

**Comment by GitNuck** [comment] 2024-02-23 20:41
> one other thought - did any other players join after you updated to 1139, whose backpacks were fine?

Yes, other players did indeed join after the update and their backpacks were fine.

**Comment by JustAHuman-xD** [comment] 2024-02-23 21:00
I highly doubt the mods had anything to do with this

**Comment by JustAHuman-xD** [comment] 2024-02-23 21:01
I've played with many mods like that including those 2 listed and never experienced this, and it wouldn't make sense that this could even be caused by a client sided mod when it's on the server. I'd like to continue looking into this

**Comment by GitNuck** [comment] 2024-02-23 22:39
Sure thing, let me know if you need anything and I'll do my best to help.  It just seems so odd that the modded clients were the only ones to have the issue.

**Comment by WalshyDev** [comment] 2024-02-24 01:12
Time also shouldn't be related

What version were you previously on before updating?
Can you retrieve the player files from the backups? Slimefun does a backup every restart. 
If yes, please restore and see if you have problems again. If you do, send the player file.

**Comment by GitNuck** [comment] 2024-02-24 04:51
I was on 1138 and I checked the backups, the backups had no backpacks listed for the problematic players.

**Comment by GitNuck** [comment] 2024-02-24 17:13
I asked the Player involved if they were sure they crafted the backpacks, and this morning he messaged me that they forgot a friend on the server made them and gave them the backpacks.  So no bug, sorry to waste everyone's time, I just went on what was reported to me.

**Comment by Boomer-1** [comment] 2024-02-24 17:27
that explains why they weren't in the specific players file, but not why they turned into cs core heads

**Comment by GitNuck** [comment] 2024-02-24 19:34
Ah OK so it looks like legit bug then.

**Comment by GitNuck** [comment] 2024-02-25 04:23
I'll ad some more to the weird.  The Player file stored in Slimefun for this player has no entries for backpacks, yet after several reboots his backpacks have remained complete with inventory, and are functional.  I used InventoryrestorePlus to give back those backpacks, but noticed that no entries for backpacks or inventory were made in the Slimefun Player file.  I checked his Inventory while the player was AFK and sure enough they are there.
![No Entries](https://github.com/Slimefun/Slimefun4/assets/88690764/ac50a458-827c-4d06-a482-8fc8287828e0)

**Comment by GitNuck** [comment] 2024-02-25 04:23
![2024-02-24_14 12 51](https://github.com/Slimefun/Slimefun4/assets/88690764/3fde4590-4215-41e8-aa29-88e4f1a21fbf)

**Comment by Boomer-1** [comment] 2024-02-25 04:27
remember the backpack is stored with the player who first opened / crafted it.

**Comment by GitNuck** [comment] 2024-02-25 04:36
> remember the backpack is stored with the player who first opened / crafted it.

Thank-you, I thought only the person who crafted the item could use the backpack, unless an AutoCrafter for SF items was used to make it, and then a gifted backpack would only work for the giftee if they were the first person to use it.

**Comment by WalshyDev** [comment] 2024-02-25 05:36
The UUID for the player who owns it is in the lore. That's the file you want look at, the items are there.

**Comment by J3fftw1** [comment] 2024-02-25 18:53
Please create a new issue for the backpack turning into a cs-corelib head.
The issue isnt related to the issue mentioned

**Closed by J3fftw1** 2024-02-25 18:53 UTC
Labels: 🐞 Bug Report, 🎯 Needs testing
