### ISSUE TITLE
Poor performance and task fail

### ISSUE THREAD

**Issue by LcyDev** [Slimefun/Slimefun4#3742] opened 2023-01-11 22:16 UTC
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

Just by removing Slimefun is a game changer, the server doesn't have slow economy responses, less ticking problems, fater server loading and no overloaded problems 

### 📑 Reproduction Steps

N/A

### 💡 Expected Behavior

It was working fine in older versions.

### 📜 Server Log

https://paste.gg/p/ConaII_/d9dd611f3fa94d328c7b5a48aeacfe41

### 💻 Server Software

Purpur

### 🎮 Minecraft Version

1.19.x

### ⭐ Slimefun version

Slimefun4 - DEV 1039 (git 3ae41)

### 🧭 Other plugins

Plugins (51): AuthMe, Auto-Tune, BetterEconomy, BKCommonLib, BlepFishing, Brewery, BungeeGuard, ChessBoards, ConsoleSpamFix, CoreProtect, CustomCrafting, DecentHolograms, DiscordSRV, EasyWhitelist, EpicRename, Essentials, EssentialsGeoIP, EssentialsSpawn, EZColors, FastAsyncWorldEdit (WorldEdit), FreedomChat, GrimAC, GSit, InventoryRollbackPlus, LiteEco, LightAPI, LocketteX, LuckPerms, My_Worlds, NBTAPI, OpenRP, PlaceholderAPI, PremiumVanish, ProtocolLib, SetSpawn, SkinsRestorer, sleep-most, Slimefun4, spark, TAB, Towny, TownyChat, TownyCultures, TownyResources, Train_Carts, Vault, ViaBackwards, ViaVersion, ViaVersionStatus, WolfyUtilities, WorldBorder, WorldGuard

**Comment by LcyDev** [comment] 2023-01-11 23:29
My bad: https://spark.lucko.me/LMVHPAJGwy

![image](https://user-images.githubusercontent.com/72966048/211940097-8277573e-ebd6-4ce5-93bb-2f58817d4634.png)

**Comment by Boomer-1** [comment] 2023-01-12 04:50
was slimefun running when the spark report was run? tps was perfect. I didn't see it in the spark report.

Additionally, these are two seperate issues. the error is one, the alleged lag is another. the plugin itself isn't laggy, it's more a result, usually, of massive player bases using tons of cargo which is a known issue and is planned for a rewrite.

I would read thru the server optimization guide which is located. here. https://github.com/Slimefun/Slimefun4/wiki/Server-Optimizations. I would also recommend switching to paper, as slimefun uses the optimizations within paper to help.

**Comment by LcyDev** [comment] 2023-01-12 06:26
Yes but it wasn't on production i will provide a better example of lagging soon.

**Comment by J3fftw1** [comment] 2023-01-12 13:13
> My bad: [spark.lucko.me/LMVHPAJGwy](https://spark.lucko.me/LMVHPAJGwy)
> 
> ![image](https://user-images.githubusercontent.com/72966048/211940097-8277573e-ebd6-4ce5-93bb-2f58817d4634.png)

this spark report is also not how we want them
Please run `/spark sampler --thread * --timeout 300`

**Comment by LcyDev** [comment] 2023-01-14 01:00
https://spark.lucko.me/Cg4cVxjCGM
https://spark.lucko.me/HljWC3h5a9

I'll update when catch lagging with the sampler

**Comment by Boomer-1** [comment] 2023-01-14 01:16
yeah, not seeing any issues

**Comment by Boomer-1** [comment] 2023-01-21 23:08
any updates? otherwise we'll close this as incomplete

**Comment by LcyDev** [comment] 2023-01-21 23:49
Honestly?
I'm so lost. Currently i'm downloading the map to remove some corrupt spawners with no TileEntities to see if that maybe does it.

When the server was on production, sometimes it DIED (Literal Death, no shutting down trail of plugins)
Basically, from one second to the next it's starting the server again, and the logs show no info.

**Comment by LcyDev** [comment] 2023-01-21 23:50
Besides that, there was some moments where the server starts lagging badly, it's rare tho.
It can start from 18 TPS until 15 TPS after some time, back to 20 constant TPS

**Comment by Phoenix-Starlight** [comment] 2023-01-22 18:04
Perhaps the tick drop is being caused by Old Gen GC. But you need to go
through and use spark to get a good idea.

**Comment by LcyDev** [comment] 2023-01-22 18:10
It could be... currently i have gc every 600 ticks.

**Comment by LcyDev** [comment] 2023-01-22 18:29
Interesting, i temporally resetted `data-storage/Slimefun` and there's no longer those delays in the startup and no economy lag issues

**Comment by LcyDev** [comment] 2023-01-22 19:16
https://paste.gg/p/ConaII_/e4504b85910649a7bb8922d5047acce0

**Comment by Boomer-1** [comment] 2023-01-22 19:34
by doing that you eliminated all the slimefun data stored at every location. all blocks will turn into vanilla. slimefun doesn't have an economy and it doesn't tie into any economy plugin. if the server is lagging, all plugins will start to lag.

I'm going to close this. if you have specific data that would prove a memory leak directly to slimefun you can open a new issue.

**Closed by Boomer-1** 2023-01-22 19:34 UTC
Labels: invalid

**Comment by LcyDev** [comment] 2023-01-22 20:32
I only removed ExoticGarden's block-storage files.
Everything seems fine.

**Comment by Phoenix-Starlight** [comment] 2023-01-25 00:06
I believe that will wipe out your plants and possibly the player head fruits
