### ISSUE TITLE
You can put backpack / shulker into backpack

### ISSUE THREAD

**Issue by Roky67** [Slimefun/Slimefun4#3772] opened 2023-02-16 16:13 UTC
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

After you put Slimefun Guide in your offhand and backpack in your main hand you can right-click and then put in whatever you like including the backpack and shulkerbox.

(Server is running on Waterfall - Yatopia)

### 📑 Reproduction Steps

1. Put Slimefun Guide in your offhand
2. Put backpack in your main hand
3. Right-click
4. Put in whatever you like

### 💡 Expected Behavior

The backpack and shulkerbox shouldn’t be able to be put inside the backpack.

### 📷 Screenshots / Videos

![image](https://user-images.githubusercontent.com/19331474/219423020-e8c4fd72-2edf-4baa-bd5c-394e558712df.png)

### 💻 Server Software

Other (please specify in your description)

### 🎮 Minecraft Version

1.18.x

### ⭐ Slimefun version

![image](https://user-images.githubusercontent.com/19331474/219423247-b7f2db16-ca4f-4297-91b2-e071e363c9c8.png)

**Comment by Boomer-1** [comment] 2023-02-16 21:31
duplicate of #3406

**Closed by Boomer-1** 2023-02-16 21:31 UTC
Labels: 🚩 Duplicate
