### ISSUE TITLE
Effects of Slime Armor not refreshing in time

### ISSUE THREAD

**Issue by marvjosh1** [Slimefun/Slimefun4#3366] opened 2021-12-08 12:04 UTC
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

When wearing slime armor (specifically leggings + boots), the effects do not refresh in time, but run out, you have no effects for ~5 seconds, before they come back again.

### 📑 Reproduction Steps

1. Get Slime leggins + boots
2. Put them on
3. Watch the effect run and not refreshing in time
(also see video below)

### 💡 Expected Behavior

I expected the potion effects of the slime armor to not run out and being refreshed in time

### 📷 Screenshots / Videos

https://youtu.be/5s0REwwbgx0

### 💻 Server Software

Purpur

### 🎮 Minecraft Version

1.17.x

### ⭐ Slimefun version

https://i.imgur.com/lPALDtr.png
https://i.imgur.com/dSPPAfb.png

**Comment by variananora** [comment] 2021-12-08 12:08
This is probably not a bug but more like a config settings/tps drops. Can you check your `config.yml` under `armor-update-interval` ? probably it is too long and making it 'not refeshing in time'

**Comment by TheBusyBiscuit** [comment] 2021-12-08 12:08
What did you set your `armor-update-interval` to?
Looks like it is set way too high

**Comment by marvjosh1** [comment] 2021-12-08 12:19
Ah sorry, it was set at 20, not sure why the default value was modified.
I put it back to the standard value of 10, that should work when the effect lasts 15s, right?

**Comment by variananora** [comment] 2021-12-08 12:56
Yes it should work normally, I'll close this issue for now, if you are still experiencing some issues, feel free to go to our Discord for help.

**Closed by variananora** 2021-12-08 12:56 UTC
Labels: invalid
