### ISSUE TITLE
Industrial Miner

### ISSUE THREAD

**Issue by Gerardgc** [Slimefun/Slimefun4#3403] opened 2022-01-02 15:46 UTC
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

Hello in the game when you use the industrial miner the first time when ends mining sends you a message with the total ore amount that the chest contains but the second time and the third fort... it says 0 and didn't mine anything i com probed that if the miner don't have any mineral down him doesn't work, and I think in that case to modify the message to say there is any ore here pls move the industrial miner to another place.

### 📑 Reproduction Steps

Use the industrial miner the advanced or the other one time as the usual.

When the industrial miner has been finished the first time, activate it again.

When the miner ends the second time, break the ground under the industrial miner and put different ores like coal iron diamonds Redstone... count the quantity of ores that you put and activate the miner.

When the miner ends for the third time it would say if you put 30 ores you mined 30 ores.

For the last time without putting anything, reactivate the miner and when it ends it would say you mined 0 ores again.

### 💡 Expected Behavior

I expect when the industrial miner can't find any ore, that tells that to you in the chat.

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.18.x

### ⭐ Slimefun version

![Captura de pantalla (6)](https://user-images.githubusercontent.com/42694861/147881135-049fbcf1-9315-47fc-9776-2b5bb052e8db.png)

**Comment by Boomer-1** [comment] 2022-01-02 15:49
you cannot mine in the same place, as it pulls the ores out of the ground when it mines.  you have to move the basic one at least 7 blocks away and the advanced 11 blocks. If you don't you end up mining the same ground, in which there are no more ores.

**Comment by TheBusyBiscuit** [comment] 2022-01-02 17:53
Closing this as invalid, if you want to suggest a better message, post the suggestion on discord or make a pull request with the corresponding code changes.
But this is definitely not a bug...

**Closed** 2022-01-02 17:52 UTC
Labels: invalid
