### ISSUE TITLE
sometimes grappling hook drops leads and arrows

### ISSUE THREAD

**Issue by TomWiskis** [Slimefun/Slimefun4#3711] opened 2022-11-01 10:37 UTC
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

grappling hook drops leads and arrows.

### 📑 Reproduction Steps

1.get grappling hook
2.double right clicking or multiple right clicking

### 💡 Expected Behavior

Just work and not drop another items

### 📷 Screenshots / Videos

https://youtu.be/Nso0FG8O4tQ

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.19.x

### ⭐ Slimefun version

build 1035 DEV

### 🧭 Other plugins

nothing else

**Comment by Boomer-1** [comment] 2022-11-01 11:02
unable to produce this. what other plugins are on your server

**Comment by Boomer-1** [comment] 2022-11-01 11:06
you were in creative, have you tested in survival?

**Comment by TomWiskis** [comment] 2022-11-01 11:06
Clear server. Only Slimefun. Yes, tested on survival

**Comment by Boomer-1** [comment] 2022-11-01 11:11
I'd like to see it in survival. you have to charge the multi-tool to use it properly.

**Comment by TomWiskis** [comment] 2022-11-01 11:11
> you were in creative, have you tested in survival?

Clear server. Only Slimefun. Yes, i tested in survival. the same

**Comment by Boomer-1** [comment] 2022-11-01 11:15
it took a long time to confirm it. the creative didn't help as the tool isn't charged and it wasn't being used right. that's why i asked for a survival video, but I finally got it to happen.

**Comment by variananora** [comment] 2022-11-01 12:51
it should be a duplicate of https://github.com/Slimefun/Slimefun4/issues/2352 since the core issues are the same.

**Comment by TomWiskis** [comment] 2022-11-01 13:18
> it should be a duplicate of #2352 since the core issues are the same.

yeah. is it. sorry. I dont find this.

**Closed** 2022-11-01 13:19 UTC
Labels: 🚩 Duplicate, 🧨 Confirmed Bug
