### ISSUE TITLE
Can't craft item from enchant crefting table

### ISSUE THREAD

**Issue by PhawatPK** [Slimefun/Slimefun4#4170] opened 2024-04-14 10:36 UTC
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

I Can't craft any item from enchant crefting table

### 📑 Reproduction Steps

1.I buid enchant crefting table
2.I put item anathing correct
3. it cant craft

### 💡 Expected Behavior

it can craft

### 📷 Screenshots / Videos

![image](https://github.com/Slimefun/Slimefun4/assets/126486934/f5d391a2-97e2-409a-b4fb-8bf7e551dd81)
![image](https://github.com/Slimefun/Slimefun4/assets/126486934/f3c5263b-7d77-46cd-8f33-d61ebab1113a)

### 💻 Server Software

Spigot

### 🎮 Minecraft Version

1.20.x

### ⭐ Slimefun version

dev 1145

### 🧭 Other plugins

![image](https://github.com/Slimefun/Slimefun4/assets/126486934/55234e14-6258-4c3d-987b-5419e8194a9e)

**Comment by Boomer-1** [comment] 2024-04-14 14:24
you have something on your server causing this problem. we have over 2000 servers running without issue. are you in some protected area, such as world guard?

**Comment by Boomer-1** [comment] 2024-04-14 14:26
also what are you trying to craft in the image? have you tried other recipes?

**Comment by Boomer-1** [comment] 2024-04-14 14:39
actually going to close this as this is not a bug but user error. please discuss this on the slimefun discord as we can help troubleshoot what you may have done wrong.

**Closed by Boomer-1** 2024-04-14 14:39 UTC
Labels: invalid
