### ISSUE TITLE
Explosive pickaxe [OUTPUT CHEST]

### ISSUE THREAD

**Issue by Niko302** [Slimefun/Slimefun4#3039] opened 2021-05-09 16:26 UTC
## :round_pushpin: Description (REQUIRED)

What's needed:
Explosive Pickaxe, Output Chest

If You fill the chest with items and break a block next to it with the Explosive Pickaxe, the chest stays in place with all items inside but also drops the items.

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

1. Place an Output Chest
2. Fill the Output Chest with items you want to duplicate.
3. Break a block next to the Output Chest with an Explosive Pickaxe

## :bulb: Expected behavior (REQUIRED)

Break the chest and drop the content.

## :scroll: Server Log

If needed will be added by server owner.

## :open_file_folder: /error-reports/ Folder

If needed will be added by server owner.

## :compass: Environment (REQUIRED)

 - Server software: 
Purpur git-Purpur-1053 (MC: 1.16.5)
Slimefun DEV - 906 (git 7a06dc30)
Metrics-Module #22
Java 11

Backwards compatibility enabled!

Installed Addons: (6)
  DyedBackpacks vDEV - 14 (git 0a051b2b)
  SFCalc vDEV - 20 (git 29ba88c6)
  Residence v4.9.2.11
  EcoPower vDEV - 4 (git 2a08d31d)
  MobCapturer vDEV - 15 (git a42c9e0c)
  ExoticGarden vDEV - 76 (git d148a362)

**Comment by WalshyDev** [comment] 2021-05-09 16:30
Dupe of #3036

**Closed by WalshyDev** 2021-05-09 16:30 UTC
Labels: invalid, 🚩 Duplicate
