### ISSUE TITLE
Soulbound Runes do not function.

### ISSUE THREAD

**Issue by MagmaBro123** [Slimefun/Slimefun4#3876] opened 2023-06-28 22:06 UTC
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

Title. Dropping a Soulbound Rune onto an item does nothing.

(Using Pufferfish.)

### 📑 Reproduction Steps

Try applying a Soulbound Rune to an item.

### 💡 Expected Behavior

The Soulbound Rune being consumed and the item getting its Soulbound effect.

### 📷 Screenshots / Videos

![2023-06-28_16 05 13](https://github.com/Slimefun/Slimefun4/assets/51277766/1d1ba279-3930-40be-a9f0-762d5dc9e1f4)

### 📜 Server Log

N/A. No errors.

### 📂 `/error-reports/` folder

N/A. No errors.

### 💻 Server Software

Other (please specify in your description)

### 🎮 Minecraft Version

1.20.x

### ⭐ Slimefun version

![2023-06-28_16 06 26](https://github.com/Slimefun/Slimefun4/assets/51277766/75a5155f-e996-4d9e-8e54-62d42fd300e9)
![2023-06-28_16 06 28](https://github.com/Slimefun/Slimefun4/assets/51277766/bc977e46-6295-4aa7-9bb2-755758f70b57)

### 🧭 Other plugins

Happens with and without other plugins.

**Comment by JustAHuman-xD** [comment] 2023-06-28 22:28
Currently cant reproduce its working fine for me

**Comment by JustAHuman-xD** [comment] 2023-06-28 22:28
Try throwing the item down, waiting a second or 2 and then throwing the rune

**Comment by Boomer-1** [comment] 2023-06-28 22:30
I ran with core slimefun only and tried multiple times, tossing different items first and not once did the rune work

**Comment by JustAHuman-xD** [comment] 2023-06-28 22:33
how long did you wait inbetween throwing the item and the rune?

**Comment by Boomer-1** [comment] 2023-06-28 22:34
idk, maybe a second. it's always been nearly instant in the past.

**Comment by Boomer-1** [comment] 2023-06-28 22:38
i just tried doing different time lengths from 1-5 seconds before tossing the item, and vice versa and not once did the rune work.

**Comment by JustAHuman-xD** [comment] 2023-06-28 22:38
interesting

**Comment by JustAHuman-xD** [comment] 2023-06-28 22:39
ill try updating my server, on 1.19.2 it works fine, but im not on 1.20

**Comment by MagmaBro123** [comment] 2023-07-18 03:26
Bump? Is this ever gonna be fixed?

**Comment by Boomer-1** [comment] 2023-07-18 03:32
when the dev's have time they will work on it. there are higher priorities than this, and they do this on their own free time. please be patient.

**Comment by Boomer-1** [comment] 2023-07-19 16:48
we have confirmed there is a problem on the specific versions.

**Comment by variananora** [comment] 2023-07-21 04:46
Can we have the video on how you apply the soulbound runes? I can't seems to replicate it.

**Comment by SrMonsterYT** [comment] 2023-07-23 18:08
I have the same problem

video: https://youtu.be/mPx4Vn6Uni0

slimefun and server version: https://prnt.sc/rxLwY6en-43S

**Comment by JustAHuman-xD** [comment] 2023-07-23 18:14
This might be only a bug with pufferish then

**Comment by JustAHuman-xD** [comment] 2023-07-23 18:14
As both of you are using it

**Comment by Boomer-1** [comment] 2023-07-23 18:36
we are still waiting on someone to show a video of it, tossing the item first, then the rune not working.

**Comment by Boomer-1** [comment] 2023-07-23 18:37
if you read the lore on the rune, it says to toss the rune on an already dropped item. in other words, the rune must be second. srmonsteryt, you didn't follow the instructions on the rune

**Comment by MagmaBro123** [comment] 2023-07-23 19:16
I did. You tested this already.

**Comment by Boomer-1** [comment] 2023-07-23 20:05
right now it's working perfectly fine when following the lore. you did not upload a link to a video showing the item being dropped first, then the rune. that's what we are asking for

**Comment by MagmaBro123** [comment] 2023-07-23 22:10
Some items work, others don't. The rune is very finicky and requires trying this several times on some stuff.

**Comment by Boomer-1** [comment] 2023-07-23 23:11
please recorda video following the steps as it is working as intended for us.

**Comment by CarterMane** [comment] 2023-07-24 00:10
> This might be only a bug with pufferish then

It might be, but I've found ways to still soulbind it even with a pufferfish server

**Comment by SrMonsterYT** [comment] 2023-07-26 17:48
a player made a video using it and it seems that if you wait a few seconds before throwing the rune it works

video: https://www.youtube.com/watch?v=_d33onDFPFI

**Comment by Boomer-1** [comment] 2023-07-26 21:46
specifically the rune asks for the item to be dropped first. that is the first video that has confirmed what we found from our testing, since that's on the lore.

**Comment by Boomer-1** [comment] 2023-07-26 21:46
unless someone has proof to the contrary, we'll close this.

**Comment by Violet-Nonbloosom** [comment] 2023-07-31 01:39
Wait a minute, I have replicated it at spigot servers.

Replication is as below.

https://github.com/Slimefun/Slimefun4/assets/86547296/6972a14f-077e-40e0-afc4-0727003cdd08

Replication environment is as below.

![图片](https://github.com/Slimefun/Slimefun4/assets/86547296/e540df1c-fe2e-4c36-b3b2-d5d4d75f30c6)

**Closed** 2023-08-01 21:58 UTC
Labels: 🐞 Bug Report, 🧨 Confirmed Bug
