### ISSUE TITLE
New Autocrafters do not work in Spigot

### ISSUE THREAD

**Issue by trekinsanity** [Slimefun/Slimefun4#2899] opened 2021-03-22 07:18 UTC
## :round_pushpin: Description (REQUIRED)

No sparkles and no items being crafted.

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

1. I setup both autocrafters to craft items. I had power and a chest.
2.  I setup a recipe for ladder, lever, sticks, chests, and Thai Tea. Nothing happened. No sparkles and no items being crafted.
3. Note: variananora and jeffrey@🐼.kz helped me on discord.
4. We tried Paper and it resolved the issue.

## :bulb: Expected behavior (REQUIRED)

All above items to be crafted.

## :scroll: Server Log

no erros in log file.

## :open_file_folder: /error-reports/ Folder

none.

## :compass: Environment (REQUIRED)

 - Server Software:  Spigot version git-Spigot-db99f82-a021e33 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
 - Minecraft Version: 1.16.5
 - Slimefun Version: sf version: vDev - 847 (git 001e7654)

**Comment by variananora** [comment] 2021-03-22 07:20
Quick notes on this:
The crafting process is working fine on Spigot, just the changing Recipe process isn't working on Spigot.

Will post a video soon for better visuals.

**Comment by variananora** [comment] 2021-03-22 07:25
Update probably this is the culprit.
https://github.com/Slimefun/Slimefun4/blob/001e7654aa13026bc2f1ab03c028a89ca1015804/src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/auto_crafters/VanillaAutoCrafter.java#L64-L66

**Comment by TheBusyBiscuit** [comment] 2021-03-22 08:17
> Update probably this is the culprit.
> 
> Spigot has no PaperLib.
> 
> https://github.com/Slimefun/Slimefun4/blob/001e7654aa13026bc2f1ab03c028a89ca1015804/src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/auto_crafters/VanillaAutoCrafter.java#L64-L66

PaperLib is part of the Slimefun jar.
It is a compatibility bridge to allow the use of Paper features and fallback to Spigot alternatives if Paper was not found.

**Comment by variananora** [comment] 2021-03-22 08:19
> PaperLib is part of the Slimefun jar.
> It is a compatibility bridge to allow the use of Paper features and fallback to Spigot alternatives if Paper was not found.

Well not sure code wise what caused it tho. I don't really understand it. lmao.

**Comment by TheBusyBiscuit** [comment] 2021-03-22 14:14
Any news regarding videos or reproduction steps?
Otherwise I will close it off as "invalid" / "Cannot reproduce".

**Comment by variananora** [comment] 2021-03-22 14:33
Step to repro:

(Left Side of Auto Crafter):
0. Use Paper or it's fork.
1. Put Vanilla Auto-Crafter (also with electricity)
2. Crouch + Right Click to update the recipe
3. Watch it could update it and craft the items
4. Restart to Spigot
5. Try to update the recipe or removing (you can't)
6. But crafting process is still working

(Right Side of Auto Crafter):
(Use the same numbering for same time)
4. Use Spigot
5. Try to add recipe to Vanilla Auto-Crafter
6. It said that it updated but it isn't and can't make the items.

Vid: https://youtu.be/b_AXAO5F4R0

**Comment by TheBusyBiscuit** [comment] 2021-03-22 14:36
I see, thanks.
I think I know what's happening there, should be an easy fix.

**Closed** 2021-03-22 14:43 UTC
Labels: 🐞 Bug Report, 🧨 Confirmed Bug
