### ISSUE TITLE
An Error occurred while initializing SlimefunItems

### ISSUE THREAD

**Issue by voila1106** [Slimefun/Slimefun4#3513] opened 2022-04-01 05:53 UTC
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

Slimefun report an error when server is starting.

java.lang.NoSuchFieldError: WHITE_CANDLE

candles are 1.17 item, my server is 1.16.5
plugin is loaded finally, but lost many items. No cargo and many machines.

### 📑 Reproduction Steps

1. put slimefun.jar into plugins folder
2. start server

### 💡 Expected Behavior

slimefun load correctly

### 📷 Screenshots / Videos

![image](https://user-images.githubusercontent.com/40945986/161202404-bf3a64a6-8bf3-4e74-a7f3-1558155d42c6.png)
![image](https://user-images.githubusercontent.com/40945986/161201980-c92e7df7-c971-4046-bbd5-725e6bcadd6a.png)
![image](https://user-images.githubusercontent.com/40945986/161202076-3e99463c-0877-489f-8b3f-5d6774883b48.png)

### 📜 Server Log

https://pastebin.com/m8ZGh2RC

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.16.x

### ⭐ Slimefun version

![image](https://user-images.githubusercontent.com/40945986/161202536-64e466bf-06c0-4b81-9714-6c2b2cf3a3bb.png)

### 🧭 Other plugins

![image](https://user-images.githubusercontent.com/40945986/161202617-95ede711-7c38-4318-8fab-961b3d929eb1.png)

**Comment by variananora** [comment] 2022-04-01 05:57
duplicate of #3504

**Closed by variananora** 2022-04-01 05:57 UTC
Labels: 🐞 Bug Report, 🚩 Duplicate
