### ISSUE TITLE
Duplication bug of slimefun block/heads using CrateReloaded plugin

### ISSUE THREAD

**Issue by EagL3-GIT** [Slimefun/Slimefun4#3728] opened 2022-12-15 17:08 UTC
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

I found out this duplication bug which kinda breaking the whole server when u know about it.

### 📑 Reproduction Steps

1. u take crate key (cratereloaded plugin) and destroy that slimefun block/head with crouching
2. it drops the exact duplicate (original block stays there) and yes, its working in survival mode too

### 💡 Expected Behavior

It should not drop slimefun head/block at all when u break it with a physical key. (CrateReloaded)

### 📷 Screenshots / Videos

https://cdn.discordapp.com/attachments/922843416130363462/1052969049568591962/Minecraft_2022.12.15_-_16.21.42.01.mp4

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.19.x

### ⭐ Slimefun version

Paper git-Paper-307 (MC: 1.19.2)
Slimefun DEV - 1035 (git 0b7c656d)
Metrics-Module #28
Java 17
 
Installed Addons: (12)
Networks vDEV - 45 (git ade6fbd0)
CMILib v1.2.4.1
InfinityExpansion vDEV - 140 (git 0098d2fb)
AureliumSkills vBeta 1.3.11
ShopGUIPlus v1.80.1
LiteXpansion vDEV - 182 (git d3800398)
WestCore v1.2-SNAPSHOT
Residence v5.1.0.1
FluffyMachines vDEV - 127 (git cf047dcf)
CMI v9.2.6.1
ItemsAdder v3.3.0-beta-r11
HeadLimiter v23

**Comment by variananora** [comment] 2022-12-16 00:31
Duplicate of #3574. Will close this one and furthe discussion will be held there.

**Closed** 2022-12-16 00:32 UTC
Labels: 🚩 Duplicate
