### ISSUE TITLE
Crate "key" item from CrateReloaded duplicates Slimefun "head" items if mining them.

### ISSUE THREAD

**Issue by mrcoffee1026** [Slimefun/Slimefun4#3574] opened 2022-05-31 04:39 UTC
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

"Key" item can be used to mine Slimefun head items which will duplicate those items... will both "break" and leave in-tact the Slimefun head giving the user the head into inventory while leaving the original head in place (producing infinite heads if repeated).

Found this technique would also work on Slimefun vanilla blocks... sometimes.  Seemed to mostly work when mining from the top face down although it doesn't always.

Video testing with CrateReloaded helper: https://vimeo.com/709927942?embedded=true&source=vimeo_logo&owner=99159429

Also created ticket with CrateReloaded:
https://github.com/Hazebyte/CrateReloaded/issues/553

### 📑 Reproduction Steps

Use any crate "key" (ours is a tripwire hook with lore and enchants) to "mine" any Slimefun head item or vanilla style block and keep an eye on your inventory.

### 💡 Expected Behavior

Slimefun items should either NOT break at all (possibility to blacklist key item from breaking it?) or simply not duplicate.  This appears to be directly related to file data having to do with the items: that data being unchanged since not mined with a proper "tool" may be resulting in the duplications.

### 📷 Screenshots / Videos

https://vimeo.com/709927942?embedded=true&source=vimeo_logo&owner=99159429

### 📜 Server Log

n/a

### 📂 `/error-reports/` folder

n/a

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.18.x

### ⭐ Slimefun version

Metrics-Module #25
Java 17

Installed Addons: (42)
  GlobalWarming vDEV - 11 (git 73ff77d4)
  Networks vDEV - 34 (git eb71c14d)
  CrystamaeHistoria vDEV - 73 (git 528ad08d)
  ExtraTools vDEV - 34 (git e84a9d59)
  FoxyMachines vDEV - 57 (git 2bca6ed7)
  SlimefunOreChunks vDEV - 15 (git 2520cb23)
  SfChunkInfo vDEV - 6 (git 56940fbf)
  FNAmplifications vDEV - 73 (git 04609677)
  SimpleMaterialGenerators vDEV - 1 (git 719e1451)
  DynaTech vDEV - 165 (git 50b62512)
  ExtraGear vDEV - 13 (git c62047e2)
  InfinityExpansion vDEV - 139 (git 1e83e7af)
  CMILib v1.1.2.5
  SFCalc vDEV - 36 (git 74973a41)
  ElectricSpawners vDEV - 23 (git 6ec96773)
  ExtraHeads vDEV - 23 (git 0b59a770)
  VillagerUtil vDEV - 1 (git 0a949b19)
  MobCapturer vDEV - 17 (git c21b00a5)
  SlimyTreeTaps vDEV - 20 (git 963f0383)
  PrivateStorage vDEV - 18 (git 5832db21)
  FlowerPower vDEV - 14 (git 63a37cc0)
  SlimeTinker vDEV - 74 (git 5ae433d4)
  TranscEndence vDEV - 41 (git 98d7d47e)
  FluffyMachines vDEV - 116 (git e439acf9)
  CMI v9.1.4.7
  SupremeExpansion vDEV - 14 (git eee7f1ab)
  DyedBackpacks vDEV - 17 (git 8b329e96)
  SoundMuffler vDEV - 23 (git 2030f464)
  AlchimiaVitae vDEV - 21 (git 27b788bf)
  SlimefunWarfare vDEV - 80 (git 364331cf)
  EcoPower vDEV - 5 (git 5c1ecd68)
  HotbarPets vDEV - 38 (git fa6c871d)
  SlimefunLuckyBlocks vDEV - 36 (git 60f0c8dc)
  ExoticGarden vDEV - 78 (git 7f9a5f63)
  DankTech2 vDEV - 4 (git 803760fb)
  Liquid vDEV - 14 (git 0f5346bf)
  LiteXpansion vDEV - 155 (git 574d551a)
  SimpleUtils vDEV - 15 (git 4250fd5e)
  ElementManipulation vDEV - 21 (git b29aaa3b)
  SoulJars vDEV - 23 (git b8358a1f)
  PotionExpansion vDEV - 5 (git e2cfcd8a)
  SlimyRepair vDEV - 4 (git 790c41cb)

### 🧭 Other plugins

[00:38:43 INFO]: CrateReloaded by Will(bart7567)

**Comment by variananora** [comment] 2022-07-10 05:16
Sorry for late test tho. This is very weird, because in my testing I am able to duplicate the whole Slimefun based head WITH the NBT, so it is usable as Slimefun item... Also I'm somewhat confused that mine only work in some certain coordinates.... 
Video: https://youtu.be/nXFAo5b33tM

**Comment by mrcoffee1026** [comment] 2022-07-10 18:08
Yeah we were getting the blocks with their NBT when it was head item, always.  It was the regular vanilla blocks I was stating that the NBT wasn't duplicated, just the blocks themselves and it seemed really inconsistent as to when they would or would not (seemed to happen most often of broken from above / breaking it from the top face).  I believe the duplication only ever takes place if the item has data stored in the data file in regards to its location.  The crate key item is probably intervened with by the crate plugin to prevent breaking things or attempted to... whatever routines normally prevent breaking appear to be bypassed by Slimefun head items.

**Comment by EagL3-GIT** [comment] 2022-12-16 12:20
When u marked my repo as a duplicate of this, u should finally take care of it from May 31.

**Comment by Boomer-1** [comment] 2022-12-16 12:27
comments like that are not helpful. The dev's who work on slimefun are 100% volunteer community based. they have lives outside of slimefun. no one is paid for what they do, so drop the attitude.

**Comment by Boomer-1** [comment] 2022-12-16 13:11
closing this as EagL3-GIt has confirmed that Cratereloaded fixed their issue with how slimefun items are handled.

**Closed by Boomer-1** 2022-12-16 13:11 UTC
Labels: ✔ Resolved, 🚩 Duplicate
