### ISSUE TITLE
Task #2361 for Residence v5.0.1.1 generated an exception

### ISSUE THREAD

**Issue by DexterSK** [Slimefun/Slimefun4#3438] opened 2022-01-23 07:03 UTC
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

[08:01:34 WARN]: [Residence] Task #2361 for Residence v5.0.1.1 generated an exception
java.lang.NoSuchMethodError: 'void io.github.thebusybiscuit.slimefun4.libraries.dough.protection.ProtectionManager.registerModule(org.bukkit.Server, java.lang.String, java.util.function.Function)'
        at com.bekvon.bukkit.residence.slimeFun.SlimefunManager.lambda$0(SlimefunManager.java:23) ~[Residence5.0.1.1.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:103) ~[purpur-1.18.1.jar:git-Purpur-1503]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.18.1.jar:git-Purpur-1503]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1574) ~[purpur-1.18.1.jar:git-Purpur-1503]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:519) ~[purpur-1.18.1.jar:git-Purpur-1503]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1497) ~[purpur-1.18.1.jar:git-Purpur-1503]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1285) ~[purpur-1.18.1.jar:git-Purpur-1503]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[purpur-1.18.1.jar:git-Purpur-1503]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### 📑 Reproduction Steps

Just start server

### 💡 Expected Behavior

No errors

### 💻 Server Software

Purpur

### 🎮 Minecraft Version

1.18.x

### ⭐ Slimefun version

Slimefun vDEV - 999 (git e02eedd9)

**Comment by variananora** [comment] 2022-01-23 09:33
Duplicate of #3433 and https://github.com/baked-libs/dough/issues/128

**Closed** 2022-01-23 09:34 UTC
Labels: 🚩 Duplicate
