### ISSUE TITLE
If you attach a Cilantro or other fruit item to the cauldron and right click, the block below will always break (bedrock and all other blocks will break).

### ISSUE THREAD

**Issue by Fuwayuka** [Slimefun/Slimefun4#3753] opened 2023-01-27 12:27 UTC
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

Right-click and execute the Cilantro on the cauldron placed as shown in the image to go through the bedrock.

### 📑 Reproduction Steps

1. Place the cauldron
2. Place a cilantro next to it.
3. break the block below, whether it is bedrock or not.

### 💡 Expected Behavior

I thought the lower block was unbreakable.

### 📷 Screenshots / Videos

![2023-01-27_21 17 04](https://user-images.githubusercontent.com/99341213/215085390-60a87b0b-0623-4632-8075-cee29a5d4f58.png)
![2023-01-27_21 17 10](https://user-images.githubusercontent.com/99341213/215085408-02682b7b-21d6-4c07-bc83-7332d8cd0a3a.png)

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.19.x

### ⭐ Slimefun version

SlimeFun vDEV 1041

### 🧭 Other plugins

![2023-01-27_21 20 29](https://user-images.githubusercontent.com/99341213/215085687-85796a5e-5485-4882-914e-7de146245f2a.png)

**Comment by variananora** [comment] 2023-01-27 12:54
1. Not a Slimefun issue, this is ExoticGarden
2. Duplicate of https://github.com/TheBusyBiscuit/ExoticGarden/issues/247 and https://github.com/TheBusyBiscuit/ExoticGarden/issues/253

**Closed by variananora** 2023-01-27 12:54 UTC
Labels: 🐞 Bug Report, 🎯 Needs testing
