### ISSUE TITLE
Items disappearing in the Ancient Altar

### ISSUE THREAD

**Issue by Beaunation** [Slimefun/Slimefun4#3154] opened 2021-07-07 02:53 UTC
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

I'm trying to make a blank rune with the Ancient Altar and the items disappear before they're used and so the crafting process is interrupted and I dont get my items back.

### 📑 Reproduction Steps

I create the altar the way its supposed to be created with all 8 pedestals

I put the items in the correct orientation in the pedestals

I used the catalyst

### 💡 Expected Behavior

I expected either a blank rune to be created or my items back.

### 💻 Server Software

Purpur

### 🎮 Minecraft Version

1.17.x

### ⭐ Slimefun version

 DEV - 944 (git 84262c56)

**Comment by Boomer-1** [comment] 2021-07-07 03:01
i literally just crafted 4 of them with Dev 944 in 1.17 without issue. can you do /sf versions and upload the entire list please

**Comment by Beaunation** [comment] 2021-07-07 05:04
![image](https://user-images.githubusercontent.com/74886868/124702897-46a0df80-debf-11eb-931a-b7858f54563c.png)

**Comment by Beaunation** [comment] 2021-07-07 05:12
https://imgur.com/a/bUYryLg
Demonstrated with the earth rune but it happens with everything I use the altar for.
Video was too big to put directly into github.

**Comment by MerryHappy** [comment] 2021-07-07 05:41
it's several month ago but i have the same ploblem

**Comment by variananora** [comment] 2021-07-07 07:57
> https://imgur.com/a/bUYryLg
> Demonstrated with the earth rune but it happens with everything I use the altar for.
> Video was too big to put directly into github.

YouTube probably the best place to upload video.

Can I have your plugin list?


> it's several month ago but i have the same ploblem
> i place item down on the altar and go find other ingredient and when i comeback there're gone

Are you sure it is not because Minecraft despawn rate? (like 5mins default iirc)

**Comment by MerryHappy** [comment] 2021-07-07 12:09
> Are you sure it is not because Minecraft despawn rate? (like 5mins default iirc)
never though of that probably more than 5 min so it's normal minecraft item despawn

**Comment by Boomer-1** [comment] 2021-07-07 12:12
we proved that items will despawn after 5 minutes, or the server's set despawn rate, so this is expected.

**Comment by EpicPlayerA10** [comment] 2021-07-07 13:41
Do you have other plugins than slimefun and addons for slimefun? If yes, please send them here.

**Comment by Beaunation** [comment] 2021-07-07 17:16
> Can I have your plugin list?




> Do you have other plugins than slimefun and addons for slimefun? If yes, please send them here.

![image](https://user-images.githubusercontent.com/74886868/124802089-92866f80-df25-11eb-9cb9-58b96b31a3c7.png)

**Comment by WalshyDev** [comment] 2021-07-07 17:29
It looks like the items are just taken pretty normally from the altar. You can tell it's altar and not spawn delay because the first item placed is the last taken.

It seems to be more an issue of the altar not outputting than items being removed

**Comment by Boomer-1** [comment] 2021-07-07 20:07
could this be the drop2inventory? I've been testing and still not having any issues with just slimefun installed.

**Comment by Beaunation** [comment] 2021-07-07 22:53
> could this be the drop2inventory? I've been testing and still not having any issues with just slimefun installed.

I have drop2inventory disabled, but I'll do some testing on a server without it and see if it still breaks.

**Comment by Beaunation** [comment] 2021-07-07 23:08
> > could this be the drop2inventory? I've been testing and still not having any issues with just slimefun installed.
> 
> I have drop2inventory disabled, but I'll do some testing on a server without it and see if it still breaks.

Still occurs with drop2inventory removed, however, on a server with no plugins other than luckperms, slimefun and vault, it does not occur.

**Comment by WalshyDev** [comment] 2021-07-08 00:00
> > > could this be the drop2inventory? I've been testing and still not having any issues with just slimefun installed.
> > 
> > 
> > I have drop2inventory disabled, but I'll do some testing on a server without it and see if it still breaks.
> 
> Still occurs with drop2inventory removed, however, on a server with no plugins other than luckperms, slimefun and vault, it does not occur.

Make a test server with all your plugins and remove them one by one until you find the cause. Once you find it also post it here so others know

**Comment by 100petr** [comment] 2021-07-17 08:21
Same issue purpur 1.17.1

https://user-images.githubusercontent.com/29830635/126030951-5e490ff0-2661-498c-a8b8-4f03c24a02d2.mp4

**Comment by variananora** [comment] 2021-07-17 08:29
> Same issue purpur 1.17.1
> It also disappears on PaperMC 1.17.1 It will remain on Spigot and will not disappear.
> 
> https://user-images.githubusercontent.com/29830635/126030951-5e490ff0-2661-498c-a8b8-4f03c24a02d2.mp4
> 
> 

not a slimefun issue, check item-alt-despawn on paper.yml.

**Comment by 100petr** [comment] 2021-07-17 08:36
So I'm going to keep trying, I chose cobblestone at random, but other sf items don't disappear without other plugins, yes on a normal server.

**Comment by J3fftw1** [comment] 2021-07-17 09:59
Cobblestone is in the default config

**Comment by variananora** [comment] 2021-07-21 11:26
@Beaunation Sorry for the tag, it's been two weeks. Have you found the issue yet?

**Comment by variananora** [comment] 2021-08-09 06:05
Closing this because there is no update on it. You could reopen this or create a new issue.

**Closed by variananora** 2021-08-09 06:05 UTC
Labels: invalid

**Comment by fabegalo** [comment] 2022-05-16 15:22
When will the items disappear after the server restart?
