### ISSUE TITLE
ender lump I made with air ?

### ISSUE THREAD

**Issue by vinerSAFE** [Slimefun/Slimefun4#3313] opened 2021-10-08 20:34 UTC
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

in **grind stone** is it posible to make **ender lump I**  from air ? it have to :)
cus in recipes in page 3 of **grind stone** Said

### 📑 Reproduction Steps

put in plugins folder and just run the server 

### 💡 Expected Behavior

if its is not bug so can we have infinit ender lump I ?!!
its ok?

### 📷 Screenshots / Videos

![۲۰۲۱-۱۰-۰۸_۲۳ ۴۶ ۴۰](https://user-images.githubusercontent.com/92184101/136620100-df8ac3c3-8a34-4ccb-bdc6-79db987fd7c4.png)

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.17.x

### ⭐ Slimefun version

979

### 🧭 Other plugins

plugins with paper-1.17.1-304 : 
EconomyShopGUI-3.9.0
EssentialsX-2.19.0
PowerRanks-1.9.9R3
Slimefun4-979
Vault-1.7.3
ViaVersion-4.0.1

**Comment by Boomer-1** [comment] 2021-10-08 20:57
Please close this. this is a duplicate of #3286

**Comment by variananora** [comment] 2021-10-09 00:06
Seems like this is a different issue. I tested a version pre-dough and the issue can't be replicated. I think this has something to do with dough or those commit between RC-27/RC-28...

**Closed as completed** 2021-10-12 14:48 UTC
Labels: 🐞 Bug Report, ✔ Resolved, 🧨 Confirmed Bug
