### ISSUE TITLE
Multi-Tool is not cancelling the block break event properly

### ISSUE THREAD

**Issue by SideLo98** [Slimefun/Slimefun4#3689] opened 2022-10-11 21:01 UTC
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

While using multi-tool to harvest crops, mine/dig blocks etc to get paid for MoneyHunter's job the multitool prevents the block from breaking but somehow players still gets paid infinitely.

### 📑 Reproduction Steps

1. grow any crop
2. break it using any multi tool
3. The crop will not break but still will drop money infinitely

### 💡 Expected Behavior

it should prevent the block break event (or some other technical term i dunno)

### 📷 Screenshots / Videos

https://streamable.com/vq7lfr

### 📜 Server Log

not required

### 📂 `/error-reports/` folder

no errors

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.19.x

### ⭐ Slimefun version

https://ibb.co/vjXn9Yg
https://postimg.cc/s1P1x1kf

### 🧭 Other plugins

MoneyHunters and NexEngine (dependency for MoneyHunters)

**Comment by Boomer-1** [comment] 2022-10-11 22:13
slimefun items don't drop money. thats another plugin interfering with slimefun

**Comment by Boomer-1** [comment] 2022-10-11 22:13
I'll let a dev close this out in case sf is interferring

**Comment by SideLo98** [comment] 2022-10-12 05:31
> slimefun items don't drop money. thats another plugin interfering with slimefun

that's correct MoneyHunters plugin does the money drop but normally it should only pay when the block(sugar cane in this case) gets really broken/harvested. this happens with multi-tool in hand only

**Comment by Phoenix-Starlight** [comment] 2022-10-14 01:23
Then the plugin should integrate to dough, most likely.

**Comment by TheBusyBiscuit** [comment] 2022-10-17 15:11
@Phoenix-Starlight This has nothing to do with dough.

I had a look at this "MoneyHunters" plugin and the issue is pretty self-explaining.
They are listening to this event on the wrong priority: https://github.com/nulli0n/MoneyHunters-spigot/blob/master/Basic/src/main/java/su/nightexpress/moneyhunters/basic/manager/job/listener/JobListenerGeneric.java#L92

The event itself is not modified by the plugin, it only listens to the outcome of the event and should therefore run on the priority `MONITOR`, not `HIGHEST`.
This is not a Slimefun issue.

**Closed by TheBusyBiscuit** 2022-10-17 15:11 UTC
