### ISSUE TITLE
Grappling Hook Lead Duping

### ISSUE THREAD

**Issue by lePro7483** [Slimefun/Slimefun4#3471] opened 2022-02-23 17:58 UTC
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

While using a Grappling Hook to Travel, i tried spam clicking it as i was blocked, and i got 2free leads, i retried spam clicking and seems if there is a bit of lags or right clicking the "arrow", it gives a free lead (Waterfall <- Tuinity Server)

### 📑 Reproduction Steps

spam click and seems if there is a bit of lags or right clicking the "arrow", it gives a free lead

### 💡 Expected Behavior

I just expected to get no items
Dont get free leads?

### 💻 Server Software

Other (please specify in your description)

### 🎮 Minecraft Version

1.16.x

### ⭐ Slimefun version

![image](https://user-images.githubusercontent.com/100308543/155378677-3eabdc32-5263-4e62-b6ee-783fe5237cb3.png)

**Comment by variananora** [comment] 2022-02-24 01:07
Duplicate of https://github.com/Slimefun/Slimefun4/issues/2352
The core issue are still the same.

**Closed by variananora** 2022-02-24 01:07 UTC
Labels: 🐞 Bug Report, 🚩 Duplicate
