### ISSUE TITLE
Slimefun Concurrent Exception

### ISSUE THREAD

**Issue by NIKIBG12** [Slimefun/Slimefun4#3950] opened 2023-08-18 21:13 UTC
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

Error in console, appeared several days at least once a day,

### 📑 Reproduction Steps

Error in console.

### 💡 Expected Behavior

Error in console.

### 📜 Server Log

https://pastebin.com/70L91Gtg

### 💻 Server Software

Purpur

### 🎮 Minecraft Version

1.20.x

### ⭐ Slimefun version

![sf versions](https://github.com/Slimefun/Slimefun4/assets/76884337/dc986688-851f-48a3-903e-e82a541d2c6d)

**Comment by mishonenchev** [comment] 2023-08-22 20:13
+1 facing the same exception

**Comment by variananora** [comment] 2023-10-05 05:41
Hey sorry for the late response, do you still get this error with the latest version? This is really quite difficult to debug. Any other info would be appreciated!

**Comment by NIKIBG12** [comment] 2023-10-12 16:17
With the latest versions I haven't seen the error again.

**Comment by TheBusyBiscuit** [comment] 2023-10-16 12:12
Duplicate of #3696

**Closed by TheBusyBiscuit** 2023-10-16 12:12 UTC
Labels: 🐞 Bug Report, 🎯 Needs testing
